# This is a basic workflow to help you get started with Actions

name: Invoke a script

permissions:
  pull-requests: write

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  do-the-script:
    name: Do something special
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require(".github/workflows/invokableScript/invokableScript.js")
            await script({github, context, core, exec})