name: Release

permissions:
  contents: write
  pull-requests: write

on:
  # Only runs on demand
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry run"
        required: true
        type: boolean
        default: true

jobs:
  lock-branch:
    name: Lock the branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          # Here create branch lock rule
          # Pass rule id through as an output so it can be deleted at the end
          script: |
            console.log("Locking the branch...");

  release:
    name: Release a new version
    runs-on: ubuntu-latest
    needs: [lock-branch]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require(".github/workflows/scripts/release.cjs");
            await script({github, context, core, exec});

  unlock-branch:
    name: Unlock the branch
    runs-on: ubuntu-latest
    needs: [lock-branch, release]
    steps:
      - uses: actions/github-script@v7
        with:
          # Here delete branch lock rule
          script: |
            console.log("Unlocking the branch...");