name: Release

permissions:
  contents: write
  pull-requests: write

on:
  # Only runs on demand
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry run"
        required: true
        type: boolean
        default: true

jobs:
  lock_branch:
    name: Lock the branch
    runs-on: ubuntu-latest
    outputs:
      lockRulesetId: ${{ steps.lock_branch.outputs.result }}
    steps:
      - id: lock_branch
        uses: actions/github-script@v7
        with:
          result-encoding: string
          # Here create branch lock rule
          # Pass rule id through as an output so it can be deleted at the end
          script: |
            const branchName = context.ref.replace("refs/heads/", "");
            console.log(`Locking branch ${ branchName }...`);
            const { data: lockRuleset } = await github.rest.repos.createRepoRuleset({ repo: context.repo.repo, owner: context.repo.owner, name: `Lock ${ branchName } for bump` });
            console.log(`Locked the branch.  Ruleset ID: ${ lockRuleset.id }`);
            return lockRuleset.id;

  release:
    name: Release a new version
    runs-on: ubuntu-latest
    needs: [lock_branch]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require(".github/workflows/scripts/release.cjs");
            await script({github, context, core, exec});

  unlock_branch:
    name: Unlock the branch
    runs-on: ubuntu-latest
    needs: [lock_branch, release]
    steps:
      - uses: actions/github-script@v7
        with:
          # Here delete branch lock rule
          script: |
            console.log("Unlocking the branch...");
            console.log("Deleting ${{ needs.lock_branch.outputs.lockRulesetId }}...");
